name: JSON-RPC Relay

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-relay:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Hedera Solo with Relay
        uses: ./
        with:
          installRelay: true
          relayPort: 7546

      - name: Wait for Relay to be ready
        run: sleep 15 

      - name: Test Relay Connection
        run: |
          echo "Testing JSON-RPC Relay..."
          curl -X POST http://localhost:7546 \
            -H "Content-Type: application/json" \
            -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'
